# Read File

In [1]:
!gdown 1E2GfSpRKGq9Oq5iC1y1hxnO2XeA6jlfc

Downloading...
From: https://drive.google.com/uc?id=1E2GfSpRKGq9Oq5iC1y1hxnO2XeA6jlfc
To: /content/spam.csv
100% 480k/480k [00:00<00:00, 107MB/s]


In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [6]:
df['spam']=df.Category.apply(lambda x:1 if x=='spam' else 0)

In [9]:
df.head(10)

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0
5     spam  FreeMsg Hey there darling it's been 3 week's n...     1
6      ham  Even my brother is not like to speak with me. ...     0
7      ham  As per your request 'Melle Melle (Oru Minnamin...     0
8     spam  WINNER!! As a valued network customer you have...     1
9     spam  Had your mobile 11 months or more? U R entitle...     1

# Train test split

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [15]:
X_train.shape

(4457,)

In [16]:
y_train.shape

(4457,)

In [17]:
X_train

2396               Babe, I'm back ... Come back to me ...
1122    Do you want 750 anytime any network mins 150 t...
5536    Aiyah ok wat as long as got improve can alread...
3879         What you need. You have a person to give na.
123     Todays Voda numbers ending 7548 are selected t...
                              ...                        
4039                             Hope you are not scared!
5151    No problem with the renewal. I.ll do it right ...
4348    U 447801259231 have a secret admirer who is lo...
1833                          What time is ur flight tmr?
5196    Spook up your mob with a Halloween collection ...
Name: Message, Length: 4457, dtype: object

In [18]:
X_train.values


array(["Babe, I'm back ... Come back to me ...",
       'Do you want 750 anytime any network mins 150 text and a NEW video phone for only five pounds per week call 08000776320 now or reply for delivery Tomorrow',
       'Aiyah ok wat as long as got improve can already wat...', ...,
       'U 447801259231 have a secret admirer who is looking 2 make contact with U-find out who they R*reveal who thinks UR so special-call on 09058094597',
       'What time is ur flight tmr?',
       'Spook up your mob with a Halloween collection of a logo & pic message plus a free eerie tone, txt CARD SPOOK to 8007 zed 08701417012150p per logo/pic'],
      dtype=object)

In [20]:
type(X_train.values)

numpy.ndarray

# Create bag of words representation using CountVectorizer

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7705 sparse matrix of type '<class 'numpy.int64'>'
	with 59395 stored elements in Compressed Sparse Row format>

In [46]:
X_train_cv

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
v.vocabulary_

In [32]:
v.get_feature_names_out()[1771]

'cheery'

In [47]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [58]:
np.where(X_train_np[0]!=0)

(array([1192, 1200, 1910, 4417, 6909]),)

In [70]:
v.get_feature_names_out()[1192]

'babe'

In [66]:
X_train

2396               Babe, I'm back ... Come back to me ...
1122    Do you want 750 anytime any network mins 150 t...
5536    Aiyah ok wat as long as got improve can alread...
3879         What you need. You have a person to give na.
123     Todays Voda numbers ending 7548 are selected t...
                              ...                        
4039                             Hope you are not scared!
5151    No problem with the renewal. I.ll do it right ...
4348    U 447801259231 have a secret admirer who is lo...
1833                          What time is ur flight tmr?
5196    Spook up your mob with a Halloween collection ...
Name: Message, Length: 4457, dtype: object

In [65]:
X_train[2396]

"Babe, I'm back ... Come back to me ..."


# Train the naive bayes model

In [75]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)


MultinomialNB()

In [76]:
X_test_cv = v.transform(X_test)

# Evaluate Performance

In [77]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       973
           1       0.99      0.95      0.97       142

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [82]:
emails = [
    'Lets catch up tommorow',
    'Hey Tahmid, can we get together to watch footbal game tomorrow?',
    'Upto 10% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 0, 1])

# Train the model using sklearn pipeline and reduce number of lines of code

In [79]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [80]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [81]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       973
           1       0.99      0.95      0.97       142

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



link --> https://colab.research.google.com/drive/1FuPNNgsLVFTIKp3WtMOSUEb8qxBV-uGm?usp=sharing